server:
  port: 8090
logging:
  config: classpath:logback-spring-dev.xml
  
subscribe:
  threadPool:
    corePoolSize: 1000
spring:
  mqtt:
    puburl: tcp://192.168.153.133:1883
    url: tcp://192.168.153.133:1883
    topics: $share/group//ip_push/resp/mqtt-push-svr001/+,$share/group//ip_push/req/+/mqtt-push-svr001
  devtools:
    reload:
      trigger-file: reloadtrigger
  kafka:
    bootstrap-servers: 192.168.153.133:9092
  redis:
    database: 1
    host: 192.168.153.134
    port: 6379
    password: redis
    timeout: 3000
    pool:
      max-idle: 8       # 连接池中的最大空闲连接，默认值也是8
      min-idle: 0       # 连接池中的最小空闲连接，默认值也是0
      max-active: 8     # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
      max-wait: -1      # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出
