server:
  port: 80
  servlet:
    context-path: /iot/nip/adapter/mqtt
  jetty:
    accesslog:
      enabled: true
      filename: /var/log/iot_core/nip/adapter/mqtt/access-yyyy_MM_dd.log
      file-date-format: yyyy_MM_dd
      append: true
      retention-period: 30
      date-format: yyyy/MM/dd HH:mm:ss Z

spring:
  profiles:
    active: dev
  kafka:
    client-id: iot-core-nip-adapter-mqtt
    consumer:
      group-id: iot-core-nip-adapter-mqtt-group
      auto-offset-reset: earliest
      enable.auto.commit: false
      normal-topic: iotcore-dw-normal-topic
      prior-topic: iotcore-dw-prior-topic
      batch-size: 1000
    producer:
      normal-topic: iotcore-up-normal-topic
      prior-topic: iotcore-up-prior-topic
  redis:
    cache:
      database: 0
      timeout: 30
      lettuce:
        pool:
          max-active: 2
          max-idle: 2
          max-wait: -1
          min-idle: 0
        shutdown-timeout: 100
    event:
      database: 2
      timeout: 30
      lettuce:
        pool:
          max-active: 2
          max-idle: 2
          max-wait: -1
          min-idle: 0
        shutdown-timeout: 100
      expire: 86400
